
package semestralniprace1_lode;

/**
 *
 * @author Enzy
 */
public class jframeTop20 extends javax.swing.JFrame {

    /** Creates new form jframeTop20 */
    public jframeTop20() {
        initComponents();

		  this.setVisible(true);		  
    }

	/**
	 * Nastave viditelnost okna a aktualizuj data
	 * @param b
	 */
	@Override
	public void setVisible(boolean b) {
		if(b){
			jlHighscore.setText("Nahrávám data z databáze...");
			Top20 tp_highscore = new Top20();
			jlHighscore.setText(tp_highscore.getFormatedList());
		}
		super.setVisible(b);
	}
	

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jpPlocha = new javax.swing.JPanel();
      jlNadpis = new javax.swing.JLabel();
      jbSchovat = new javax.swing.JButton();
      jlHighscore = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("TOP 20");
      setBackground(new java.awt.Color(0, 0, 0));
      setForeground(new java.awt.Color(255, 255, 255));
      setMinimumSize(new java.awt.Dimension(311, 541));
      setResizable(false);

      jpPlocha.setBackground(new java.awt.Color(0, 0, 0));
      jpPlocha.setForeground(new java.awt.Color(255, 255, 255));
      jpPlocha.setMinimumSize(new java.awt.Dimension(311, 541));
      jpPlocha.setPreferredSize(new java.awt.Dimension(311, 541));

      jlNadpis.setFont(new java.awt.Font("28 Days Later", 0, 64)); // NOI18N
      jlNadpis.setForeground(new java.awt.Color(255, 255, 255));
      jlNadpis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jlNadpis.setText("TOP 20");

      jbSchovat.setBackground(new java.awt.Color(0, 0, 0));
      jbSchovat.setFont(new java.awt.Font("28 Days Later", 1, 24)); // NOI18N
      jbSchovat.setForeground(new java.awt.Color(255, 255, 255));
      jbSchovat.setText("Schovat");
      jbSchovat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
      jbSchovat.setFocusPainted(false);
      jbSchovat.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbSchovatActionPerformed(evt);
         }
      });

      jlHighscore.setBackground(new java.awt.Color(0, 0, 0));
      jlHighscore.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
      jlHighscore.setForeground(new java.awt.Color(204, 204, 204));
      jlHighscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jlHighscore.setText("Načítám highscore z databáze...");

      javax.swing.GroupLayout jpPlochaLayout = new javax.swing.GroupLayout(jpPlocha);
      jpPlocha.setLayout(jpPlochaLayout);
      jpPlochaLayout.setHorizontalGroup(
         jpPlochaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPlochaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jpPlochaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jlHighscore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
               .addComponent(jbSchovat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
               .addComponent(jlNadpis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
            .addContainerGap())
      );
      jpPlochaLayout.setVerticalGroup(
         jpPlochaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jpPlochaLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jlNadpis)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jlHighscore, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addGap(18, 18, 18)
            .addComponent(jbSchovat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jpPlocha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jpPlocha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

	 private void jbSchovatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSchovatActionPerformed
		this.dispose();
	 }//GEN-LAST:event_jbSchovatActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframeTop20().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jbSchovat;
   private javax.swing.JLabel jlHighscore;
   private javax.swing.JLabel jlNadpis;
   private javax.swing.JPanel jpPlocha;
   // End of variables declaration//GEN-END:variables

}
